<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerP94gzmz\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerP94gzmz/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerP94gzmz.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerP94gzmz\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerP94gzmz\appProdProjectContainer([
    'container.build_hash' => 'P94gzmz',
    'container.build_id' => '617058e2',
    'container.build_time' => 1609173053,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerP94gzmz');
