<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBw2nlxh\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBw2nlxh/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerBw2nlxh.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerBw2nlxh\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerBw2nlxh\appProdProjectContainer([
    'container.build_hash' => 'Bw2nlxh',
    'container.build_id' => '85dc50fc',
    'container.build_time' => 1607888718,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBw2nlxh');
