<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJitqfbu\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJitqfbu/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerJitqfbu.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerJitqfbu\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerJitqfbu\appProdProjectContainer([
    'container.build_hash' => 'Jitqfbu',
    'container.build_id' => 'a80d6661',
    'container.build_time' => 1608215864,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJitqfbu');
